question 1

In [7]:
import pandas as pd
data={
    'Tid':[1,2,3,4,5,6,7,8,9,10],
    'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'Marital Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
    'Taxable Income':['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
    'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}
df=pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
1    2     No        Married           100k    No
2    3     No         Single            70k    No
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No
9   10     No         Single            90k   Yes

question 2

In [10]:
selected_rows = df.iloc[[0, 4, 7, 8]]
print(selected_rows)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
4    5     No       Divorced            95k   Yes
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No

question 3

In [37]:
### 1. Select rows from index 3 to 7
rows_3_to_7 = df.iloc[3:8]
print(rows_3_to_7)

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes

In [38]:
### 2. Select rows from index 4 to 8, and columns from index 2 to 4
rows_4_to_8_cols_2_to_4 = df.iloc[4:9, 2:5]
print(rows_4_to_8_cols_2_to_4)

  Marital Status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

In [39]:
### 3. Select rows from index 4 to 8, and columns from index 2 to 4
all_rows_cols_1_to_3 = df.iloc[:, 1:4]
print(all_rows_cols_1_to_3)

  Refund Marital Status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes        Married           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

question 4

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [40]:
import pandas as pd

file_path = '/content/drive/MyDrive/Iris.csv'


df_from_drive = pd.read_csv(file_path)
print("CSV loaded successfully!")
display(df_from_drive.head())

CSV loaded successfully!

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

question 5

In [21]:
# Delete row 4 (index 4)
df_modified = df_from_drive.drop(index=4)

# Delete column 3 (index 3). Get the column name at index 3.
column_to_delete = df_modified.columns[3]
df_modified = df_modified.drop(columns=[column_to_delete])

print("DataFrame after deleting row 4 and column 3:")
display(df_modified.head())

DataFrame after deleting row 4 and column 3:

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

question 6

In [41]:
import pandas as pd
import os

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01', '2021-02-10', '2010-11-25'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Bonus': [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees_df = pd.DataFrame(data)


csv_file_path = 'employees.csv'
employees_df.to_csv(csv_file_path, index=False)

print(f"'{csv_file_path}' created successfully in the current directory.")

display(employees_df)

'employees.csv' created successfully in the current directory.

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [42]:

df_employees = pd.read_csv('employees.csv')

print("Dataset loaded successfully into 'df_employees' DataFrame.")

Dataset loaded successfully into 'df_employees' DataFrame.


a) Shape (number of rows and columns) of the DataFrame

In [24]:
print(f"Shape of the DataFrame: {df_employees.shape} (rows, columns)")

Shape of the DataFrame: (5, 10) (rows, columns)


b) Summary of the DataFrame (data types and non-null counts)

In [25]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

c) Generate descriptive statistics

In [26]:
display(df_employees.describe())

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

d) Display the first 5 rows and last 3 rows of the dataset

In [27]:
print("First 5 rows:")
display(df_employees.head(5))

print("\nLast 3 rows:")
display(df_employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

e) Calculate the following statistics:

In [28]:
# i. The average salary of employees
average_salary = df_employees['Salary'].mean()
print(f"i. The average salary of employees: ${average_salary:,.2f}")

# ii. The total bonus paid to all employees
total_bonus = df_employees['Bonus'].sum()
print(f"ii. The total bonus paid to all employees: ${total_bonus:,.2f}")

# iii. The youngest employee's age
youngest_age = df_employees['Age'].min()
print(f"iii. The youngest employee's age: {youngest_age} years")

# iv. The highest performance rating
highest_rating = df_employees['Rating'].max()
print(f"iv. The highest performance rating: {highest_rating}")

i. The average salary of employees: $60,000.00
ii. The total bonus paid to all employees: $27,500.00
iii. The youngest employee's age: 28 years
iv. The highest performance rating: 4.7

### f) Sort the DataFrame by the Salary column in descending order.

In [29]:
df_sorted_by_salary = df_employees.sort_values(by='Salary', ascending=False)
print("DataFrame sorted by Salary in descending order:")
display(df_sorted_by_salary)

DataFrame sorted by Salary in descending order:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### g) Add a new column that categorizes employees based on their performance rating:
i. Excellent for ratings >= 4.5
ii. Good for ratings >= 4.0 but < 4.5
iii. Average for ratings < 4.0

In [30]:
def categorize_rating(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0 and rating < 4.5:
        return 'Good'
    else:
        return 'Average'

df_employees['Performance_Category'] = df_employees['Rating'].apply(categorize_rating)
print("DataFrame with 'Performance_Category' column:")
display(df_employees)

DataFrame with 'Performance_Category' column:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### h) Identify missing values in the DataFrame.

In [31]:
print("Missing values in the DataFrame:")
print(df_employees.isnull().sum())

Missing values in the DataFrame:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### i) Rename the Employee_ID column to ID.

In [32]:
df_employees.rename(columns={'Employee_ID': 'ID'}, inplace=True)
print("DataFrame after renaming 'Employee_ID' to 'ID':")
display(df_employees)

DataFrame after renaming 'Employee_ID' to 'ID':

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### j) Find all employees who:
i. Have more than 5 years of experience.
ii. Belong to the IT department.

In [33]:
employees_more_than_5_years_exp = df_employees[df_employees['Years_of_Experience'] > 5]
print("Employees with more than 5 years of experience:")
display(employees_more_than_5_years_exp)

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [34]:
employees_it_department = df_employees[df_employees['Department'] == 'IT']
print("Employees belonging to the IT department:")
display(employees_it_department)

Employees belonging to the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### k) Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary.

In [35]:
df_employees['Tax'] = df_employees['Salary'] * 0.10
print("DataFrame with new 'Tax' column:")
display(df_employees)

DataFrame with new 'Tax' column:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### l) Save the modified DataFrame (with added columns) to a new CSV file.

In [36]:
new_csv_file_path = 'modified_employees.csv'
df_employees.to_csv(new_csv_file_path, index=False)
print(f"Modified DataFrame saved successfully to '{new_csv_file_path}'.")

Modified DataFrame saved successfully to 'modified_employees.csv'.